- cumulus_etl/chart_review/cli.py
- cumulus_etl/chart_review/downloader.py
- cumulus_etl/deid/scrubber.py
- cumulus_etl/errors.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/config.py
- cumulus_etl/etl/studies/covid_symptom/covid_ctakes.py
- cumulus_etl/etl/studies/covid_symptom/covid_tasks.py
- cumulus_etl/etl/tasks.py
- cumulus_etl/fhir/__init__.py
- cumulus_etl/fhir/fhir_client.py
- cumulus_etl/fhir/fhir_schemas.py
- cumulus_etl/fhir/fhir_utils.py
- cumulus_etl/formats/base.py
- cumulus_etl/formats/deltalake.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- cumulus_etl/loaders/i2b2/transform.py
- pyproject.toml
- tests/fhir/test_fhir_client.py
- tests/fhir/test_fhir_utils.py
- tests/test_bulk_export.py
- tests/test_deltalake.py
- tests/test_etl_tasks.py
- tests/test_ndjson_loader.py
This helps downstream SQL not have to worry about whether the incoming data has a particular optional FHIR field (which before, would mean that the Athena schema didn't define it, which would yield a SQL error).
Now, all the R4 FHIR fields will be represented at least at the toplevel, and SQL can rest a bit easier.
> feat: when writing delta lake tables, include a shallow FHIR schema

- cumulus_etl/formats/deltalake.py
- cumulus_etl/loaders/i2b2/extract.py
- tests/test_deltalake.py
Pandas converts integer columns with nulls to float columns by default. This confused our new schema merging feature.
So now we ask Pandas to use more modern column types (ones that can handle nulls better). This fixes the schema issue.
BUT it might introduce incompatibilities with existing tables. If so, the easiest fix is to blow away the table and recreate it.
> fix: avoid schema-mismatch errors for int columns that have nulls

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- README.md
- docs/setup/sample-runs.md
- Drop the whole section about asking for a private access key
- Refresh the main README to be less "this is what Cumulus is" now that we have a public docs site for that kind of thing, and make it a more traditional open source project README with pointers to contributing and the like.
> docs: clean up docs to reflect our public status

- cumulus_etl/deid/ms-config.json
- cumulus_etl/deid/scrubber.py
- tests/data/mstool/input/Condition.1.json
- tests/data/mstool/input/Medication.1.json
- tests/data/mstool/input/MedicationRequest.2.json
- tests/data/mstool/output/Condition.1.json
- tests/data/mstool/output/Medication.1.json
- tests/data/mstool/output/MedicationRequest.2.json
- tests/deid/test_deid_scrubber.py
- Start anonymizing contained "id" fields (that's an oversight that should have already happened, but contained resources are not widely used and I don't expect this to require much backfilling)
- Add an MS tool config for Medication, so that any MedicationRequests that contain a Medication will allow its interesting values through.
> fix: allow contained Medication resources through

- cumulus_etl/chart_review/cli.py
- cumulus_etl/common.py
- cumulus_etl/deid/codebook.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/convert/cli.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/store.py
- tests/deid/test_deid_codebook.py
- tests/deid/test_deid_scrubber.py
- tests/etl/test_etl_cli.py
- tests/test_chart_cli.py
- tests/test_common.py
Also, reduce the number of times that the codebook writes itself out (i.e. stop writing the main codebook every time we write out the mappings)
> fix: make writes to remote locations atomic

- cumulus_etl/common.py
The previous atomic commit had a bug that wrote out zero-length files due to a missing flush.
This is an emergency weekend stop-gap fix. Will add tests next week and investigate a little more.
> fix: stop writing out zero-length files for anything < 5MB

- cumulus_etl/chart_review/cli.py
- cumulus_etl/common.py
- cumulus_etl/deid/codebook.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/convert/cli.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/store.py
- tests/deid/test_deid_codebook.py
- tests/deid/test_deid_scrubber.py
- tests/etl/test_etl_cli.py
- tests/test_chart_cli.py
- tests/test_common.py
OK another problem has been observed with the atomic file change, where a file isn't completely written out (missing last chunk), seemingly even with the recent flush change.
Reverting this all until I can properly debug.
> fix: revert previous atomic fixes - incomplete files being written

- cumulus_etl/chart_review/cli.py
- cumulus_etl/common.py
- cumulus_etl/deid/codebook.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/convert/cli.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/store.py
- pyproject.toml
- tests/deid/test_deid_codebook.py
- tests/deid/test_deid_scrubber.py
- tests/etl/test_etl_cli.py
- tests/s3mock.py
- tests/test_chart_cli.py
- tests/test_common.py
- tests/utils.py
This PR contains 3 commits:
- Old PR #243 (reviewed, reverted)
- Old PR #244 (not reviewed, reverted)
- New commit that fixes the remaining issue.
This new commit has the actual fix to a bug introduced in #243:
```
-        return root.fs.open(path, mode=mode, encoding="utf8")
+        with root.fs.open(path, mode=mode, encoding="utf8") as file:
+            yield file
```
The original commit changed `open_file` (a method that returns a file) to `_atomic_open` (a context manager that returns a file), inadvertently dropping the bit where we were actually using the file as a context manager itself, which means the file was not being closed and could have lingering data not committed to disk.
Easy to miss, hard to find.
I've also updated our testing to catch the several error cases that …
> Return of the Atomic Writes

- cumulus_etl/fhir/fhir_auth.py
- cumulus_etl/fhir/fhir_client.py
- tests/covid_symptom/test_nlp_results.py
- tests/fhir/test_fhir_client.py
- tests/test_bulk_export.py
- tests/test_chart_cli.py
I've tested that this sends the header to the Epic sandbox and doesn't do it for the Cerner sandbox. But I have never experienced the case where Epic requires this header (and to get a user/password to test the non-OAuth flow that does require it would require asking that of the Epic security team). So I'm just going to assume this is great. We can hear from our partners on Epic about its efficacy. Seems harmless and likely to work (based on reports of them patching this in basically).
> fix: add Epic vendor quirk to pass Epic-Client-ID

- cumulus_etl/chart_review/cli.py
- cumulus_etl/chart_review/downloader.py
- cumulus_etl/chart_review/selector.py
- cumulus_etl/cli_utils.py
- cumulus_etl/common.py
- cumulus_etl/deid/mstool.py
- cumulus_etl/formats/deltalake.py
- cumulus_etl/loaders/__init__.py
- cumulus_etl/loaders/base.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- cumulus_etl/loaders/i2b2/loader.py
- docs/vendors/epic.md
- tests/test_chart_cli.py
- tests/test_deltalake.py
If both the lake table and the update rows have `meta.lastUpdated`, only push the update row if it is actually a newer version.
This should let folks with `meta.lastUpdated` support more safely mix and match batches of ndjson without having to stress about when each batch was exported from the EHR.
Unfortunately Epic doesn't provide this field, so this benefit is limited to other EHRs.
> feat(deltalake): don't overwrite newer rows if we can avoid it

- .github/workflows/docker-hub.yaml
- compose.yaml
- docs/performance.md
- docs/setup/sample-runs.md
This adds a new docker-hub.yaml workflow that builds and pushes any commit to main into Docker Hub directly.
And uses that built image in the compose file.
You can see the results of test runs here: https://hub.docker.com/r/smartonfhir/cumulus-etl/tags
> feat: add GitHub workflow to build and push to Docker Hub

- compose.yaml
I was overzealous when adding support for the pre-built ETL image. I removed the flag that let you build it via docker compose build.
So let's put that back.
> fix: allow building the docker image via compose.yaml again

- cumulus_etl/fhir/fhir_auth.py
- tests/fhir/test_fhir_client.py
Let them be themselves, man!
Specifically:
- Don't inspect their smart config for any declarations - no EHR is very good about filling that out.
- Don't require FHIR spec compliant key algorithms - if the server accepts it, who are we to judge
> fix: don't be so strict when connecting to a FHIR server

- cumulus_etl/etl/tasks/factory.py
- tests/etl/test_tasks.py
Prior to this commit, tasks were either:
A) In alphabetical order if no task list was provided
B) In arbitrary order if a task list was provided (the task list was turned into a set at some point in the processing)
**No task list**
Let's address (A) first - what order should we run them if no task list is given? While alphabetical is fine, we have an opportunity to reduce writes to the cached codebook mapping file.
Every time we come across a new encounter or patient ID, we first write out the mapping file before writing the batch to the output target.
To reduce churn there, we can simply run the tasks with the highest density of new IDs first and have fewer writes of the mapping file.
So in the case of no provided task order, we now run 'encounter' first, then 'patient', then the rest in …
> feat: order tasks to minimize codebook writes

- cumulus_etl/common.py
- cumulus_etl/deid/mstool.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/fhir/fhir_client.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- Bulk export gets a spinner
- Each task gets 3 progress bars (prep, batches, finalize)
- After the ETL run, print a final success message
Old:
New:
[Screencast](https://github.com/smart-on-fhir/cumulus-etl/assets/1196901/071f350d-b8f8-4ac8-87b6-971b932c3818)
> feat: use progress bars in a lot more places

- cumulus_etl/etl/studies/covid_symptom/covid_tasks.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/etl/tasks/basic_tasks.py
This allows for tasks whose output is not 1:1 with their input. For example, medicationrequest or covid_symptom__nlp_results.
Before, their total batch count might be over or under counted. Now, the reading bar will always match the input progress, and the writing bar will be indeterminate or finished while taking a reading breather.
I could have just left off the `Writing` bar, and had the `Reading` bar have momentary-but-unexplained pauses. But then you have the issue of the last batch written. I didn't want 100% on the reading bar for 30 minutes with no explanation (or arguably worse, save a bit at the end and leave it at 99% for 30 minutes).
I also figured it was better to reset the existing `Writing` bar (rather than have a growing list of `Batch 1`, `Batch 2` etc bars) because that …
> fix: use separate reading/writing progress bars during tasks

- compose.yaml
- cumulus_etl/etl/studies/covid_symptom/covid_tasks.py
- cumulus_etl/etl/studies/hftest/__init__.py
- cumulus_etl/etl/studies/hftest/hf_tasks.py
- cumulus_etl/etl/tasks/__init__.py
- cumulus_etl/etl/tasks/factory.py
- cumulus_etl/nlp/__init__.py
- cumulus_etl/nlp/huggingface.py
- cumulus_etl/nlp/utils.py
- tests/convert/test_convert_cli.py
- tests/etl/test_tasks.py
This task is not run by default, and it is more of a toy than a production-ready task right now.
It just asks Llama2 to summarize clinical notes.
There was no prompt engineering to improve results, yet.
Here's how you run it:
```
export HUGGING_FACE_HUB_TOKEN=xxx
docker compose up llama2 --wait  # this will take several minutes
docker compose run cumulus-etl --task hftest__summary ...
```
Note that Llama2 requires a GPU to run.
> feat: add new llama2 NLP test task

- compose.yaml
- cumulus_etl/etl/cli.py
- cumulus_etl/loaders/i2b2/loader.py
- cumulus_etl/loaders/i2b2/transform.py
- tests/i2b2_mock_data.py
- Allow overriding CUMULUS_HUGGING_FACE_URL
- Show batch size with commas
- Change i2b2 argument name 'codebook' to 'display_codes' to avoid confusion with the de-id Codebook elsewhere in the ETL
> fix: misc minor tweaks

- cumulus_etl/common.py
- tests/test_common.py
Before, we allowed files of this format:
1.Patient.ndjson
Patient.1.ndjson
1.Patient.1.ndjson
Patient.ndjson
But now we also allow files that look like:
Patient.string.here.ndjson
1.Patient.string.here.ndjson
This loosening is to help with organizing your files - maybe you have an export of Observation labs and want to denote that in the filename, like 1.Observation.labs.ndjson or something.
> feat: allow input ndjson files to have non-numeric filename parts

- compose.yaml
- cumulus_etl/etl/studies/hftest/hf_tasks.py
- cumulus_etl/nlp/huggingface.py
This also fixes a few bugs:
- bad default internal docker url
- not long enough of a timeout waiting for a llama2 answer
- but most importantly, increase `max_new_tokens` value so that answers are a reasonable length
The ultimate end goal of this llama2 support is likely the 70B model. But this is a further march in that direction, while still being able to run on reasonably available hardware.
For an example synthea clinical note, it generates reasonable sounding (and accurate to the note) summaries like:
```
Sure! Here is a summary of the clinical note:                                   
The patient is a 44-year-old non-Hispanic white female who presents with no     
chief complaint. She has a history of part-time employment, not being in the    
labor force, full-time employment, …
```
> feat: bump WIP llama2 image to 13B model (from 7B)

- cumulus_etl/chart_review/cli.py
- cumulus_etl/chart_review/downloader.py
- cumulus_etl/chart_review/labelstudio.py
- cumulus_etl/chart_review/selector.py
- docs/chart-review.md
- tests/fhir/test_fhir_client.py
- tests/test_chart_cli.py
- tests/test_chart_labelstudio.py
This adds a couple quality-of-life improvements to chart-review mode:
- Notes are now grouped by encounter, with each note clearly demarked inside a larger text document.
- Notes now have a header with their note type label (e.g. "Admission MD") plus their real & anonymized IDs
- The encounter ID (real+anon) plus all the contained DocRef IDs (real+anon) are also pushed as Label Studio metadata, which will show up in exports if folks want to do some post-processing.
This should land along with an announcement.
> feat(chart-review): group notes by encounter, show real & anon IDs

- compose.yaml
The llama2 docker compose stanza was missing a profile, which meant it was launching for all profiles.
Setting an "hf-test" profile fixes that.
> docker: stop launching llama2 for every profile

- cumulus_etl/etl/studies/covid_symptom/covid_tasks.py
- tests/covid_symptom/test_nlp_results.py
Previously, we had some BCH/i2b2-specific ED codes for BCH's i2b2 data. And the LOINC codes were supposed to be sufficient for the properly coded data coming from Cerner.
But it turns out that not all DocRefs in Cerner have proper LOINC codes, so this commit adds the same site-specific i2b2 codes but with a Cerner "system".
This should be harmless, study-wise since all these NLP symptoms are filtered down on the Library side - worst case is that we run NLP on docs we don't need to. But this now allows the Library side to expand what it looks for, if it wants.
> feat(covid-symptom): add BCH/Cerner-specific ED codes

- docs/nlp.md
> docs: emphasize LLMs and re-usable code in NLP docs

- .github/workflows/ci.yaml
- compose.yaml
- cumulus_etl/chart_review/cli.py
- cumulus_etl/chart_review/downloader.py
- cumulus_etl/chart_review/labelstudio.py
- cumulus_etl/nlp/__init__.py
- docs/chart-review.md
- tests/chart_review/test_chart_cli.py
- tests/chart_review/test_chart_labelstudio.py
In case we need to know the internal placing of doc notes, when we gather multiple notes into one note, push up the start & end of those texts.
No planned use for this right now, but I want to get this in so when we do want it, the metadata already exists.
> feat(chart-review): push internal docref spans to Label Studio

- cumulus_etl/formats/batched_files.py
- docs/deid.md
- tests/formats/test_ndjson.py
Two commits:
- One is a doc broken link fix
- The other adjusts the "ndjson format overwrite detection" code to allow for `.meta` files which NLP jobs also write out in addition to .ndjson
> A couple small fixes

- cumulus_etl/deid/ms-config.json
Turns out that the MS Anonymizer tool actually does support json comments, using C-style /* */ and // syntax.
I really thought I had tested that at some point.
So this commit just converts all the fake {"comment": "my text"} lines into real comments. And adds a comment for every field skipped (i.e. adds a comment for every field you wouldn't otherwise see because we use an allow-list)
No functionality changes. (Except de-id might be faster now that it has less fake rules to attempt to apply.)
> chore(ms-config): replace fake json comments with C-style comments

- cumulus_etl/etl/studies/covid_symptom/covid_ctakes.py
- docs/index.md
- tests/covid_symptom/test_covid_results.py
Previously, there was no way to detect the difference between a DocRef that was not processed (not an ED DocRef or an error occurred etc) vs a DocRef that had no symptoms.
Both just had zero rows in the Athena db.
This commit starts adding a single row in the nlp_results table with a null "match" column for this case.
Existing SQL should be able to gracefully handle this change. If/when we want to update the SQL to handle these kinds of DocRefs, it can be updated to treat these new rows specially. But for now, they will be ignored.
> fix: write "null match" NLP rows for DocRefs with no symptoms

- cumulus_etl/errors.py
- cumulus_etl/etl/tasks/nlp_task.py
- cumulus_etl/fhir/fhir_auth.py
- cumulus_etl/loaders/fhir/bulk_export.py
- tests/etl/test_etl_cli.py
- tests/fhir/test_fhir_client.py
Previously, if you were running an NLP task and we needed to download a clinical note but couldn't, we'd early-exit with an error and say "please provide the auth flags, kthx"
Now, we merely warn about it once but keep processing DocRefs.
This is designed to more gracefully handle some cases like BCH has, where their DocRefs contain some URLs that always error out, but the other DocRefs have been nicely inlined.
So we want to be able to run in a "no-network" context where we don't need to talk to the FHIR server at all. We just want to process the already-inlined notes.
In other contexts, where the user genuinely made a mistake and should re-run with auth parameters, this should still be plenty of notice. There is an error printed to the console, and the job is marked as failing, so the …
> feat: downgrade some fatal connection errors to warnings

- cumulus_etl/deid/philter.py
- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labelstudio.py
- docs/chart-review.md
- pyproject.toml
- tests/s3mock.py
- tests/upload_notes/test_upload_cli.py
- tests/upload_notes/test_upload_labelstudio.py
This commit deprecates --no-philter in favor of --philter=disable and adds --philter=label (and the default --philter=redact).
When --philter=label is requested, we send a prediction layer to Label Studio that highlights all the detected PHI spans for you.
This is helpful when doing manual de-identification, since philter can do some of the grunt work for you.
Example (synthea note, no PHI here):
> feat(upload-notes): add ability to tag philter spans, not redact them

- cumulus_etl/fhir/__init__.py
- cumulus_etl/fhir/fhir_utils.py
- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labelstudio.py
- pyproject.toml
- tests/fhir/test_fhir_client.py
- tests/fhir/test_fhir_utils.py
- tests/upload_notes/test_upload_cli.py
- tests/utils.py
Also:
- Order the DocRefs in an encounter by datetime
- Switch from freezegun to time-machine
Unrelatedly:
- Switch from deprecated cgi module to email module for mimetype parsing.
Fixes https://github.com/smart-on-fhir/cumulus-etl/issues/298
> feat(upload-notes): add datetimes to each DocRef header

- cumulus_etl/cli_utils.py
- pyproject.toml
pyarrow 15: https://arrow.apache.org/blog/2024/01/21/15.0.0-release/
(seems like they just removed some deprecated API - seems to work fine)
The hostname thing happens during `compose run` when we try to use network hostnames but you haven't started the service, or some other similar cases - catching that error will go down the "print a nice message" path.
> A couple tweaks: bump pyarrow and give nicer error ctakes hostname error message

- docs/setup/cumulus-aws-template.yaml
Amazon's latest visual template editor doesn't like Fn::Join but does like !Join. So give it what it wants.
I tested this in the editor (no errors) and tested a deploy, to confirm it does the split and join.
> docs: fix AWS template to avoid confusing syntax

- cumulus_etl/__init__.py
- cumulus_etl/common.py
- cumulus_etl/errors.py
- cumulus_etl/etl/tasks/nlp_task.py
- cumulus_etl/fhir/fhir_client.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/export_log.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- docs/setup/cumulus-aws-template.yaml
- pyproject.toml
- tests/etl/test_etl_cli.py
- tests/loaders/ndjson/test_bulk_export.py
- tests/loaders/ndjson/test_ndjson_loader.py
- tests/utils.py
When Cumulus ETL is running the bulk export ourselves, we now write out a bulk export log, in the standard[1] format.
This is only useful when passing an --export-to folder of course, but that ought to be the normal use case.
Also:
- Don't early exit an export if there are server-provided error messages. We'll still bail, because our exporter is very conservative. But we'll do that at the end, after we download everything. This should help with debugging issues and archiving.
[1] https://github.com/smart-on-fhir/bulk-data-client/wiki/Bulk-Data-Export-Log-Items
> feat: write out a bulk export log file when we do the export

- Dockerfile
By bumping the python in our docker images to 3.11, which has better fromisoformat() logic that can handle a "Z" suffix.
This does not yet bump our minimum Python version for the code itself, but most folks run the ETL via the docker image.
> fix: fix parsing of server timestamps when bulk exporting

- compose.yaml
- cumulus_etl/__init__.py
- cumulus_etl/etl/studies/covid_symptom/covid_tasks.py
This hopefully fixes a race condition when restarting cTAKES as we feed it new bsv files.
Also bumped ETL's version to 1.1.1 (coincidentally the same :D)
> docker: depend on ctakes 1.1.1

- cumulus_etl/common.py
- cumulus_etl/loaders/i2b2/extract.py
This PR disables the warning about context manager usage for the time being.
> Disable context generator cleanup pylint warning

- .pre-commit-config.yaml
- cumulus_etl/deid/mstool.py
It moves temporary files into their final place, and that might happen as we are trying to get the file size - so handle that exception.
> fix: be more graceful when MS tool moves files underneath us

- cumulus_etl/common.py
- cumulus_etl/formats/deltalake.py
- cumulus_etl/loaders/i2b2/extract.py
- tests/test_common.py
There was an off by one error if the last character of the ndjson file was a newline. This prevented some "reading" progress bars from every appearing finished.
This was just cosmetic though - all data was read.
> fix: allow the progress bars for reading ndjson to finish

- cumulus_etl/common.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labelstudio.py
- cumulus_etl/upload_notes/selector.py
- docs/chart-review.md
- tests/upload_notes/test_upload_labelstudio.py
Newer versions of Label Studio seem to flag dynamic labels differently than previous ones. So detect dynamic labels a different way.
Also:
- Print how many notes we are attempting to upload.
- Warn if we don't see any DocumentReference files.
- Add "-f compose.yaml" to the upload-notes example commands in the docs as a reminder that you need to be running off a compose file.
> fix(upload-notes): allow uploading to dynamic label setups again

- cumulus_etl/common.py
- cumulus_etl/etl/convert/cli.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/loaders/fhir/export_log.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- cumulus_etl/store.py
- pyproject.toml
- tests/covid_symptom/test_covid_results.py
- tests/etl/base.py
- tests/etl/test_etl_cli.py
- tests/etl/test_tasks.py
- tests/loaders/ndjson/test_bulk_export.py
- tests/loaders/ndjson/test_ndjson_loader.py
- tests/test_common.py
- tests/test_store.py
- tests/upload_notes/test_upload_cli.py
- We now load any ndjson files that cumulus-fhir-support says to.
- Root classes no longer adjust filenames from ls() -- that was a hack to solve the fact that we often looked up the right filesystem to use for a given path by examining the path - we are now more careful about passing a filesystem object around with the path.
Depends on https://github.com/smart-on-fhir/cumulus-fhir-support/pull/3
> feat: switch to cumulus-fhir-support's ndjson reading code

- pyproject.toml
I've manually tested that we can still upload notes just fine. Their release docs for 1.0 say the API we use shouldn't be impacted (though there were breaking changes on other API).
> build: bump label-studio-sdk dependency to 1.x

- docs/setup/cumulus-aws-template.yaml
These aren't necessarily used, but it's lightly helpful to have them already in place if you want to experiment with the completion tracking feature (--write-completion)
> docs: add completion tables in our AWS template

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- pyproject.toml
It's currently set to require all new & modified code to be fully covered. And to allow the current coverage score of 93% in general.
Let's see how annoying this is. :smile:
> ci: add a coverage check at end of unit tests

- .github/workflows/ci.yaml
- cumulus_etl/cli.py
- tests/etl/base.py
- tests/etl/test_etl_cli.py
- tests/test_cli.py
- tests/upload_notes/test_upload_cli.py
> tests: add some CLI tests to improve coverage

- compose.yaml
This should allow http proxies and custom CA roots.
Fixes #319 and I think #135 too.
> feat: pass common networking variables through the docker layer

- .github/workflows/ci.yaml
- cumulus_etl/__init__.py
- cumulus_etl/cli.py
- cumulus_etl/cli_utils.py
- cumulus_etl/errors.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/tasks/task_factory.py
- cumulus_etl/export/__init__.py
- cumulus_etl/export/cli.py
- cumulus_etl/fhir/fhir_client.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/export_log.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- docs/bulk-exports.md
- pyproject.toml
- tests/etl/test_etl_cli.py
- tests/export/test_export_cli.py
- tests/fhir/test_fhir_client.py
- tests/loaders/ndjson/test_bulk_export.py
This new command is quite simple. It just takes a URL and an output folder. The usual auth and export args (like --since) are accepted.
You can also filter exported resources by task with --task.
But even if you don't use --since or --task, you can provide an export URL that has _since, _type, _typeFilter, whatever you want.
In addition:
- "--task=help" will now print a list of task names and exit.
- The traditional way to kick off a bulk export when doing an ETL job (by providing a URL as the input path) now also lets you specify custom parameters like _since or _typeFilter directly in the URL.
- Handle non-compliant servers that give us transactionTime values that aren't formatted correctly (as bulk-data-server does).
> feat: add new "cumulus-etl export" command for bulk exporting

- cumulus_etl/fhir/fhir_client.py
- cumulus_etl/loaders/fhir/bulk_export.py
- tests/fhir/test_fhir_client.py
- tests/loaders/ndjson/test_bulk_export.py
Retry each request four times (for a total of five requests) in an exponential backoff of 1, 2, 4, and 8 minutes (total of 15 minutes).
This should hopefully help when dealing with flaky EHRs.
Fixes: #334
> Retry bulk export requests that yield 5xx server errors

- cumulus_etl/deid/philter.py
- docs/nlp.md
- pyproject.toml
We do that now in the covid_symptom__nlp_results_gpt* tasks.
> docs: drop comment about no cloud LLM/NLP being implemented

- Dockerfile
- cumulus_etl/etl/tasks/basic_tasks.py
- tests/etl/test_tasks.py
If an error occurs while downloading Medication references, it's likely going to repeat itself (missing --fhir-url, server being down, etc).
So just print it once.
Fixes: #341
> medicationrequest: don't spam console with "need --fhir-url" errors

- cumulus_etl/loaders/fhir/bulk_export.py
- docs/bulk-exports.md
- docs/setup/sample-runs.md
- tests/loaders/ndjson/test_bulk_export.py
If the bulk export server provides an array of error messages or an array of deleted resources, make sure we persist those on disk.
Previously, we only printed the error messages to the console. We still do that, but also write them to an error/ subfolder.
Previously, we ignored any deleted resources.
Now we write them to a deleted/ subfolder.
This matches the behavior of bulk-data-client.
This is part 1 of #167.
Next step is actually processing a `deleted/` folder in any input ndjson.
> bulk: store "deleted" and "error" results in export subfolders

- .github/workflows/ci.yaml
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/config.py
- cumulus_etl/etl/convert/cli.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/formats/base.py
- cumulus_etl/formats/batched_files.py
- cumulus_etl/formats/deltalake.py
- cumulus_etl/formats/ndjson.py
- cumulus_etl/loaders/__init__.py
- cumulus_etl/loaders/base.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- cumulus_etl/loaders/i2b2/loader.py
- tests/convert/test_convert_cli.py
- tests/etl/test_etl_cli.py
- tests/etl/test_tasks.py
- tests/formats/test_deltalake.py
- tests/formats/test_ndjson.py
- tests/loaders/i2b2/test_i2b2_loader.py
- tests/loaders/i2b2/test_i2b2_oracle_extract.py
- tests/loaders/ndjson/test_ndjson_loader.py
- Updates Loader classes to return any information found about deleted resources
- Updates the Delta Lake formatter to use that info to delete rows
- Updates the ndjson formatter to preserve the `deleted` metadata on disk
- Updates `convert` logic to read that preserved metadata and then carry that into the Delta Lake
As a reminder, the spec's commentary on how to handle `deleted` is in the [bulk export section](https://hl7.org/fhir/uv/bulkdata/export.html).
Fixes #167
> Parse any deleted resource IDs from bulk exports and act on it

- .github/workflows/ci.yaml
- .github/workflows/docker-hub.yaml
- Dockerfile
Using a "local version identifier" per PEP 440, the version looks like: `1.3.0+d7abeb366a8179691f3234502986dad14698a4c5`
PEP for reference: https://peps.python.org/pep-0440/
This will help distinguish ETL builds from each other while we still build directly from git.
> docker: add git revision to version during docker build

- cumulus_etl/__init__.py
- cumulus_etl/formats/deltalake.py
- pyproject.toml
- tests/etl/test_etl_cli.py
In practice, for most of our big raw tables, this will involve clustering on a single column: `id`, in which case Delta Lake falls back to a very simple ZORDER algorithm (making sure that the data files are ordered by `id`, to make looking up via `id` easy) -- which is still good, just not as sleek and cool as the full "liquid clustering" algorithm.
But it's still good to do for two reasons:
- This new paradigm is apparently the future of Delta Lake optimization, replacing normal ZORDER and partitioning. And you can't convert an existing table to it. So if we start creating clustered tables now, even if it's secretly just a ZORDER, we can benefit from future improvements to the algorithm and/or add more clustering columns if we want to.
- There are a few tables that *do* cluster by …
> Enable liquid clustering for delta lakes

- cumulus_etl/__init__.py
- cumulus_etl/cli.py
- cumulus_etl/cli_utils.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/init/__init__.py
- cumulus_etl/etl/init/cli.py
- docs/setup/sample-runs.md
- tests/init/test_init_cli.py
This will create an empty table for each basic resource that we support. This is a convenience command to get up and running faster or to refresh your database schemas in case we change them in the future.
> feat: add new `init` subcommand

- cumulus_etl/errors.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/loaders/base.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- cumulus_etl/loaders/i2b2/loader.py
- cumulus_etl/upload_notes/downloader.py
- tests/etl/test_etl_cli.py
- tests/loaders/i2b2/test_i2b2_loader.py
- tests/loaders/i2b2/test_i2b2_oracle_extract.py
- tests/loaders/ndjson/test_ndjson_loader.py
- tests/upload_notes/test_upload_cli.py
- If tasks are selected with --task or --task-filter and a needed resource is missing, we now error out.
- If tasks are not specifically selected, we now only run tasks for which resources are available (and error out if no resources exist at all)
- If --allow-missing-resources is passed, we skip both above checks and do historical behavior of running any given task with zero input rows (which pushes up a schema, cleans up the delta lake, and stamps the resource as complete in the completion tracking tables).
This addresses a lingering issue from #296, where we didn't adequately protect ourselves from incorrectly handling "empty set" inputs and wrongly marking them as complete. I've decided to go the simplest route and refuse to handle empty-sets unless specifically told to. I think this …
> Skip tasks or error out when resources are missing

- .github/workflows/docker-hub.yaml
I tested these changes and wanted to land them separately from #354 because I wanted to get a release tagged as `1` out there, so that folks that didn't want to update scripts or deal with the change yet had a fallback.
> docker: tag releases with the major version number too

- cumulus_etl/deid/ms-config.json
- cumulus_etl/deid/scrubber.py
- cumulus_etl/etl/cli.py
- cumulus_etl/etl/tasks/nlp_task.py
- docs/deid.md
- tests/data/mstool/output/Patient.1.json
- tests/data/mstool/output/Patient.2.json
- tests/data/mstool/output/Patient.3.json
- tests/deid/test_deid_scrubber.py
- tests/etl/test_etl_cli.py
- Print a report at the end of the ETL run of all extensions stripped by resource, URL, and count.
- Plus a report on resources skipped due to unrecognized modifier extensions.
- Leave stub extension in place, with just the `url` field, so that we can inspect stripped extensions in SQL if we want.
This commit allows a bunch of extensions in use today. Scanned some sample data from Cerner and Epic to find common extensions. We'll surely add to the list going forward, to avoid annoying folks with the unknown-extension warning.
Ignore the following extensions:
- http://hl7.org/fhir/StructureDefinition/iso21090-TEL-address
- http://hl7.org/fhir/StructureDefinition/rendered-value
- http://hl7.org/fhir/us/core/StructureDefinition/us-core-direct
- …
> feat: don't simply toss extensions

- .github/dependabot.yaml
- pyproject.toml
> ci: enable dependabot

- cumulus_etl/deid/scrubber.py
- cumulus_etl/etl/tasks/base.py
- tests/etl/test_tasks.py
- Add some extension URLs that Synthea generates to the scrubber's allowlist/blocklist
- If the completion table can't be written for some reason, at least flag it to the user by marking that something went wrong
> A couple small improvements

- cumulus_etl/formats/deltalake.py
- tests/formats/test_deltalake.py
Without allowing this, we can't meaningfully update rows as ETL evolves to allow more content (_data and _url fields recently, maybe future allowed extensions, that sort of thing).
This does allow more data churn, but correctness takes priority. We could maybe get both if we inserted the ETL version into every row? But for now, this is an easy tweak.
> fix: allow overwriting delta lake entries with same timestamp

- cumulus_etl/deid/ms-config.json
- cumulus_etl/deid/scrubber.py
- docs/deid.md
- pyproject.toml
- tests/deid/test_deid_philter.py
- tests/deid/test_deid_scrubber.py
Previously, we would let Observation.valueString (and its component form) through, optionally masking it with philter if you passed --philter in.
But it held PHI too often, and if we ever will use the field, it will likely be via ETL-side NLP. We don't need to keep the string intact into Athena.
So now, we unconditionally drop Observation.valueString, replacing it with a data-absent-reason extension marker (so consumers know it _was_ present).
> feat(deid): drop valueString instead of passing it through

- cumulus_etl/deid/ms-config.json
- cumulus_etl/deid/scrubber.py
- cumulus_etl/fhir/fhir_client.py
- tests/data/mstool/input/DiagnosticReport.ndjson
- tests/data/mstool/output/DiagnosticReport.ndjson
- tests/deid/test_deid_scrubber.py
Specifically, treat it the same as we treat DocumentReference.content.
- Strip data & url into _data & _url data-absent-reason extensions.
- But keep all the interesting metadata like contentType and language.
- Add Binary scope when requesting DiagnosticReport scopes.
> feat(deid): keep some fields from DiagnosticReport.presentedForm

- docs/bulk-exports.md
- tests/loaders/ndjson/test_bulk_export.py
> docs: update jwks generation commands to separate public/private keys

- cumulus_etl/etl/tasks/base.py
- tests/etl/test_etl_cli.py
- tests/etl/test_tasks.py
When iterating through the input ndjson, if we see the same row ID inside a batch, we now prefer the row that came later.
This means that our behavior is more consistent:
- If rows are in same batch, later is preferred (new)
- If rows are across batches, later is preferred (same)
This way, you can safely throw ndjson updates to your original FHIR data alongside the original data and it can reliably be processed (as long as you choose good filename ordering).
> Always prefer resource rows that come later

- cumulus_etl/fhir/__init__.py
- cumulus_etl/fhir/fhir_client.py
- cumulus_etl/fhir/fhir_utils.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/export_log.py
- tests/fhir/test_fhir_client.py
- tests/fhir/test_fhir_utils.py
- tests/loaders/ndjson/test_ndjson_loader.py
Before, we were just using some regexes on the URL, but let's actually use a parser and separate out the pieces.
This is better in general, but also happens to let us handle cases like the user putting an export URL like ".../$export?_type=..." on the shell, having the shell zero-out the $export string because it thinks it is a variable, and then us seeing a URL like "/?_type=..." (which isn't really a valid URL, but we will insert missing $export strings later in the process).
As part of this, I refactored some instances of URL parsing into one single FhirUrl class, which we can build upon in the future as needed.
> fix: improve FHIR-root-URL parsing to cover more cases

- cumulus_etl/deid/scrubber.py
Due to a missing comma, two known-but-we-want-to-silently-ignore-them extensions were being warned about instead of silently ignored:
- http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName
- http://hl7.org/fhir/StructureDefinition/rendered-value
> fix: a couple extensions were incorrectly being warned about

- cumulus_etl/deid/codebook.py
- cumulus_etl/deid/scrubber.py
- cumulus_etl/upload_notes/cli.py
- tests/deid/test_deid_codebook.py
- tests/deid/test_deid_scrubber.py
If you are uploading notes that you haven't ETL'd before, this will (a) create the codebook if you have never ETL'd and (b) update any cached mappings.
> fix(upload-notes): save the codebook after using it

- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labelstudio.py
- tests/upload_notes/test_upload_cli.py
- tests/upload_notes/test_upload_labelstudio.py
- No longer ignore matches in previous docs when grouping (whoops)
- Instead of labeling a found term with the term itself, just mark it with a generic "Keyword" label to be less noisy in the Label Studio interface (Andy request)
- Escape regex characters in highlight terms
- Improve boundary matching when a term includes non-word characters (like a + or -)
> fix(upload-notes): improve --highlight matching

- MAINTAINERS.md
- tag-release.sh
- tests/inliner/test_inliner.py
Just run ./tag-release.sh and it's updated!
> build: add script to update stable-release Docker tags

- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labelstudio.py
- tests/upload_notes/test_upload_cli.py
- tests/upload_notes/test_upload_labelstudio.py
Previously, we grouped by encounter and sorted notes inside the encounter. Now, we still sort inside an encounter but also sort among encounters for the earliest to latest. And group by patient and also sort them by earliest doc to latest doc.
Should help chart reviewers make mental sense of the notes as they go one by one.
> feat(upload-notes): sort notes by encounter/patient

- cumulus_etl/upload_notes/labelstudio.py
- tests/upload_notes/test_upload_labelstudio.py
It turns out that Label Studio can nowadays always accept a label list, it doesn't need to only be sent when dynamic labels are turned on. And always sending it helps avoid a situation when we don't think we need to send it but we do (like when there are both static and dynamic labels in play).
> fix(upload-notes): always send label list, even with static labels

- cumulus_etl/export/cli.py
- cumulus_etl/loaders/fhir/bulk_export.py
- tests/export/test_export_cli.py
- tests/loaders/ndjson/test_bulk_export.py
This helps recover from situations where the server only lets you make so many exports at once, and you don't need a previous one.
Or just to be a good citizen.
Note that the ETL normally cancels/cleans up for you in the success case. But if the ETL gets interrupted, this lets you manually clean up.
I only added this for the `export` subcommand - it didn't feel like it made as much sense in the `etl` subcommand flow. I also felt this was a rare enough case to not bother with docs about it, but I could be convinced otherwise.
> feat(export): add a --cancel option

- cumulus_etl/upload_notes/labelstudio.py
- tests/upload_notes/test_upload_labelstudio.py
Andy found Keyword to take up too much space in the Label Studio UI.
> fix(upload-notes): rename Keyword to Tag when highlighting

- cumulus_etl/loaders/fhir/export_log.py
- tests/loaders/ndjson/test_bulk_export.py
We don't ever request partial manifest pages, so this is just a logging format change to emit a few new events.
> feat: write bulk export log v2 format (with manifest events)

- .github/workflows/docker-hub.yaml
- .github/workflows/pypi.yaml
- pyproject.toml
Also, only push docker images upon release. And drop upper limits on dependencies, to make pip users' lives easier.
> build: push to pypi upon release

- compose.yaml
For images we don't control, this sets the platform version for docker images, which should allow better arm processor compatibility
> Explicitly define support image platform

- cumulus_etl/__init__.py
- cumulus_etl/loaders/fhir/export_log.py
- tests/loaders/ndjson/test_bulk_export.py
> fix: report an accurate bulk export duration in the logs

- cumulus_etl/__init__.py
- cumulus_etl/loaders/fhir/export_log.py
- tests/loaders/ndjson/test_bulk_export.py
They don't really tell us anything. Status errors will still be logged.
> feat: stop filling export logs with status_progress messages

- cumulus_etl/__init__.py
- cumulus_etl/export/cli.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- docs/bulk-exports.md
- tests/export/test_export_cli.py
- tests/loaders/ndjson/test_bulk_export.py
--type is more familiar to folks that are used to the bulk API than --task - now you can use both.
And --type-filter is helpful because manually putting a _typeFilter argument into your URL is a pain, because you have to encode it yourself.
> feat: add --type and --type-filter to export subcommand

- cumulus_etl/__init__.py
- cumulus_etl/fhir/fhir_auth.py
Some servers claim to support v2 but do not actually (Cerner)
> fix: only use v2 scopes if no other choice

- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labelstudio.py
- tests/upload_notes/test_upload_cli.py
- tests/upload_notes/test_upload_labelstudio.py
- Adds a patient_id and anon_patient_id column
- Renames the anon_id column to anon_enc_id for clarity
> feat(upload-notes): add patient ID info to label studio metadata

- cumulus_etl/__init__.py
- cumulus_etl/deid/scrubber.py
- tests/deid/test_deid_scrubber.py
It's an Epic customer extension system and there could be PHI in there (which we've seen in the wild).
> fix(deid): Strip out code/display for urn:oid:1.2.840.114350.*

- cumulus_etl/upload_notes/cli.py
- tests/upload_notes/test_upload_cli.py
The kind of errors we now simply print about instead of erroring out:
- No connection to a FHIR server
- No text/html mimetype found for an attachment
Now we just print a message to the console and keep going.
> fix(upload-notes): don't bail when errors happen

- cumulus_etl/__init__.py
- cumulus_etl/loaders/fhir/bulk_export.py
- cumulus_etl/loaders/fhir/export_log.py
- tests/loaders/ndjson/test_bulk_export.py
Previously, we followed bulk-export-client's lead and generated a new uuid for each run of the client. Which in the case of resuming a previously interrupted export, means that the same "logical" export can now have two different IDs.
Which, could be fine. But the ETL also tries to parse info from export logs like export group name and export timestamp. It's a lot easier to do that with consistent export IDs.
We maybe should also investigate making that log reading robust against clients that don't set consistent IDs, but this is an easy change for now to make this client at least a little more consistent.
(The spec does not give any required form to the ID, so as far as I can tell, it's an opaque string that we can stuff a URL into.)
> fix(export): use a consistent exportId across export restarts

- .github/workflows/docker-hub.yaml
- .github/workflows/pypi.yaml
- cumulus_etl/__init__.py
This makes it easier to release versions without needing to update the hardcoded version in the repo. Just release from github when it makes sense to.
> build: set version dynamically from tag rather than __init__.py

- cumulus_etl/common.py
- cumulus_etl/etl/tasks/basic_tasks.py
- cumulus_etl/etl/tasks/nlp_task.py
- cumulus_etl/inliner/inliner.py
- cumulus_etl/inliner/writer.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- tests/etl/test_etl_cli.py
- tests/inliner/test_inliner.py
Now that cumulus-fhir-support can return *.gz files, we need a little extra support in the ETL to process them, because the MS tool doesn't know how to read them.
So we have to decompress them before pushing data through our pipeline.
> feat(etl): support gzip input files (*.ndjson.gz)

- cumulus_etl/deid/scrubber.py
- tests/deid/test_deid_scrubber.py
Add a "masked" data-absent-reason extension behind when we drop code and display, so tools like data-metrics can know that values did exist.
> fix(deid): when stripping Epic's custom system codes, leave a note

- cumulus_etl/upload_notes/cli.py
- docs/chart-review.md
- tests/upload_notes/test_upload_cli.py
It feels surprising to folks that they need cTAKES to upload notes. And at BCH, we typically disable it all the time anyway. Let's go with the simple path by default, but allow it to be enabled.
The old --no-nlp arg will persist, but do nothing. The new --nlp arg will turn on NLP.
> feat(upload-notes): disable NLP by default

- cumulus_etl/deid/scrubber.py
- cumulus_etl/etl/tasks/base.py
- cumulus_etl/etl/tasks/basic_tasks.py
- cumulus_etl/fhir/__init__.py
- cumulus_etl/fhir/fhir_client.py
- cumulus_etl/fhir/fhir_utils.py
- cumulus_etl/inliner/cli.py
- cumulus_etl/loaders/fhir/ndjson_loader.py
- cumulus_etl/upload_notes/cli.py
- pyproject.toml
- tests/etl/test_tasks.py
- tests/fhir/test_fhir_client.py
This lets the user pre-download Medication resources and present them to the ETL alongside the MedicationRequest resources. Thus avoiding a download step and letting the ETL be disconnected from the FHIR server during the ETL.
> feat(etl): read local Medication resources when processing MedReqs

- docs/studies/covid-symptom.md
Its scope changed over time, let's not give folks the wrong impression, especially since it's now published with the respitory infection name.
Fixes https://github.com/smart-on-fhir/cumulus-etl/issues/383
> docs: refer to covid_symptom as an respitory infection study

- cumulus_etl/cli_utils.py
- cumulus_etl/etl/pipeline.py
- cumulus_etl/id_handling.py
- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labeling.py
- cumulus_etl/upload_notes/labelstudio.py
- docs/nlp/example.md
- tests/upload_notes/test_upload_cli.py
- tests/upload_notes/test_upload_labelstudio.py
Also added support for the "origin" field on an NLP label table. This lets us keep track of which model provided NLP info all the way through Label Studio and into chart-review.
> Expand the "example NLP workflow" doc to include chart-review

- cumulus_etl/cli_utils.py
- cumulus_etl/etl/nlp/cli.py
- cumulus_etl/nlp/selection.py
- tests/nlp/test_selection.py
This is instead of only allowing the --allow-large-selection flag as a way of continuing - which is used in multiple selection checks. Now you can just press "y" to continue.
Fixes https://github.com/smart-on-fhir/cumulus-etl/issues/452
> nlp: when selecting from a large athena table, prompt user

- cumulus_etl/upload_notes/cli.py
- cumulus_etl/upload_notes/labelstudio.py
- tests/upload_notes/test_upload_cli.py
- tests/upload_notes/test_upload_labelstudio.py
This uses the earliest encounter date when grouping.
Fixes https://github.com/smart-on-fhir/cumulus-etl/issues/454
> upload-notes: add a date metadata field, for downstream scripting
